Exclude bash completion for fedora rawhide
- Avoid the following error:

  Reading /home/abuild/rpmbuild/BUILD/geopm-doc-3.1.0-build/SPECPARTS/rpm-debuginfo.specpart
  Processing files: geopm-doc-3.1.0-14.1.x86_64
  Processing files: geopm-runtime-doc-3.1.0-14.1.x86_64
  Provides: geopm-runtime-doc = 3.1.0-14.1 geopm-runtime-doc(x86-64) = 3.1.0-14.1
  Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
  Processing files: geopm-service-doc-3.1.0-14.1.x86_64
  error: More than one file on a line: /geopmread
  error: More than one file on a line: /geopmwrite

  RPM build errors:
      More than one file on a line: /geopmread
      More than one file on a line: /geopmwrite

Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>