Remove short region data insertion from trace.
- WIP.
- Prob abandon?
- Possibly observed integration test regressions.

======================================================================
ERROR: test_region_runtimes (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./geopm_test_integration.py", line 521, in
test_region_runtimes
filtered_df = self.create_progress_df(data)
File "./geopm_test_integration.py", line 170, in
create_progress_df
filtered_df = pandas.concat(row_list)
File
"/usr/lib/python2.7/site-packages/pandas/core/reshape/concat.py",
line 212, in concat
copy=copy)
File
"/usr/lib/python2.7/site-packages/pandas/core/reshape/concat.py",
line 245, in __init__
raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

======================================================================
ERROR: test_runtime_regulator
(__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./geopm_test_integration.py", line 483, in
test_runtime_regulator
filtered_df = self.create_progress_df(trace_data)
File "./geopm_test_integration.py", line 170, in
create_progress_df
filtered_df = pandas.concat(row_list)
File
"/usr/lib/python2.7/site-packages/pandas/core/reshape/concat.py",
line 212, in concat
copy=copy)
File
"/usr/lib/python2.7/site-packages/pandas/core/reshape/concat.py",
line 245, in __init__
raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

Change-Id: I2be0a5179d0b086578c1951550ae417c3d980790
Signed-off-by: Brandon Baker <brandon.baker@intel.com>